language: java

jdk:
  - oraclejdk8

before_install:
  - pip install --user awscli zip
  - export PATH=$PATH:$HOME/.local/bin
  - docker-compose --version

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw test

after_success:
  - mvn jacoco:report coveralls:report
  - sh deploy.sh

branches:
  only:
  - master
